return {
PlaceObj('ModItemCode', {
	'name', "BetterZoomModScript",
	'CodeFileName', "Code/BetterZoomModScript.lua",
}),
PlaceObj('ModItemOptionChoice', {
	'name', "BetterZoomModCameraTacMaxZoom",
	'comment', "Vanilla Default = 130, Mod Default = 300",
	'DisplayName', "Maximum Camera Zoom",
	'Help', "Defines how far the camera may zoom out (Vanilla Default = 130)",
	'DefaultValue', "300",
	'ChoiceList', {
		"130",
		"200",
		"300",
		"400",
		"500",
		"600",
		"700",
		"800",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "BetterZoomModCameraTacMinZoom",
	'comment', "Vanilla Default = 65, Mod Default = 70",
	'DisplayName', "Minimum Camera Zoom",
	'Help', "Defines how far the camera may zoom in (Vanilla Default = 65)",
	'DefaultValue', "70",
	'ChoiceList', {
		"100",
		"90",
		"80",
		"70",
		"65",
		"60",
		"50",
		"40",
		"30",
		"20",
		"10",
	},
}),
-- PlaceObj('ModItemOptionChoice', {
-- 	'name', "BetterZoomModCameraTacOverviewZoom",
-- 	'comment', "Vanilla Default = 220, Mod Default = 600",
-- 	'DisplayName', "Overview Camera Zoom",
-- 	'Help', "Defines how far the camera may zoom in (Vanilla Default = 220)",
-- 	'DefaultValue', "600",
-- 	'ChoiceList', {
-- 		"100",
-- 		"200",
-- 		"220",
-- 		"300",
-- 		"400",
-- 		"500",
-- 		"600",
-- 		"700",
-- 		"800",
-- 		"1200",
-- 	},
-- }),
PlaceObj('ModItemOptionChoice', {
	'name', "BetterZoomModCameraTacZoomStep",
	'comment', "Vanilla Default = 25, Mod Default = 50",
	'DisplayName', "Zoom Step Size",
	'Help', "Defines how fast the camera zoom (Vanilla Default = 25)",
	'DefaultValue', "50",
	'ChoiceList', {
		"10",
		"25",
		"50",
		"75",
		"100",
		"125",
	},
}),
}
