return PlaceObj('ModDef', {
	'title', "Better Zoom Mod",
	'description', "Adjust the minimum and maximum zoom levels of the game. Adjust Settings via Options -> Mod Options.\n\nMany thanks to [url=https://steamcommunity.com/id/FailChapi]FAIL! Chapi[/url] and [url=https://www.nexusmods.com/jaggedalliance3/users/101291438]reyback[/url] for inspiration and support.",
	'last_changes', "Initial Release",
	'image', "Images/modicon.png",
	'id', "BetterZoomMod",
	'author', "ChrisVomRhein",
	'version_major', 1,
	'version', 00,
	'lua_revision', 233360,
	'saved_with_revision', 336921,
	'code', {
		"Code/BetterZoomModScript.lua",
	},
	'has_options', true,
	'saved', 1688225719,
	'code_hash', 5896151797841822063,
	'TagGameplay', true,
	'screenshot1', "Images/scr1.png",
	'screenshot2', "Images/scr2.png",
})