return PlaceObj('ModDef', {
	'title', "Better Zoom Mod",
	'description', "Modify the minimum and maximum zoom levels of the game. Adjust Settings via Options -> Mod Options.\n\nMany thanks to FAIL! Chapi and reyback for inspiration and support.\n\nLicense: MIT\nSource Code: https://github.com/Christian1984/jagged-alliance-3-better-zoom-mod",
	'image', "Images/modicon.png",
	'last_changes', "Fixed zoom levels during AI turns",
	'id', "BetterZoomMod",
	'content_path', "Mod/BetterZoomMod/",
	'author', "ChrisVomRhein",
	'version_major', 1,
	'version', 1,
	'version', 6,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/BetterZoomModScript.lua",
	},
	'has_options', true,
	'saved', 1690319837,
	'code_hash', -558831421540346189,
	'screenshot1', "Images/better-zoom-mod-screenshot-1.png",
	'screenshot2', "Images/better-zoom-mod-screenshot-2.png",
	'screenshot3', "Images/better-zoom-mod-screenshot-3.png",
})